# Generated by Django 3.1.1 on 2021-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='TitleSlug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
