# Generated by Django 3.1.1 on 2021-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210422_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-DateAdded']},
        ),
        migrations.AddField(
            model_name='post',
            name='DateAdded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
