# Generated by Django 3.1.1 on 2021-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20210423_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
