# Generated by Django 3.1.1 on 2021-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20210423_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='CommentCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
