# Generated by Django 3.1.1 on 2021-04-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='SlugName',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
