# Generated by Django 3.1.1 on 2021-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_category_slugname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='DateAdded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
