# Generated by Django 3.1.1 on 2021-04-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courosel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='courosels/')),
                ('Caption', models.CharField(max_length=70)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post')),
            ],
        ),
    ]
