# Generated by Django 3.1.1 on 2021-05-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_aboutsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSite',
        ),
    ]
